env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
ignorePatterns:
  - scratch
  - "*.js"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
    - FunctionDeclaration:
        parameters:
          first
      CallExpression:
        arguments:
          first
      MemberExpression:
        1
      SwitchCase:
        1
      ImportDeclaration:
        first
  max-len:
    - error
    - 120
  semi:
    - error
    - always
  quotes:
    - error
    - double
  no-unused-vars:
    - off
  no-constant-condition:
    - off
  semi-spacing:
    - error
    - before:
        false
      after:
        true
  no-empty:
    - error
    - allowEmptyCatch:
        true
  object-curly-spacing:
    - error
    - always
  array-bracket-spacing:
    - error
    - always
    - singleValue:
        false
      objectsInArrays:
        false
      arraysInArrays:
        false
  space-in-parens:
    - error
    - never
  comma-spacing:
    - error
  computed-property-spacing:
    - error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine:
        true
  eol-last:
    - error
  semi-style:
    - error
    - last
  "@typescript-eslint/no-unused-vars":
    - warn
    - destructuredArrayIgnorePattern:
        ^_
      argsIgnorePattern:
        ^_
      varsIgnorePattern:
        ^assert$|^M$
  "@typescript-eslint/no-non-null-assertion":
    - off
  "@typescript-eslint/no-explicit-any":
    - off
  "@typescript-eslint/no-unnecessary-type-assertion":
    - error
  "@typescript-eslint/no-unnecessary-condition":
    - error
    - allowConstantLoopConditions:
        true
  "@typescript-eslint/no-this-alias":
    - error
    - allowedNames:
      - self
  "@typescript-eslint/no-floating-promises":
    - "error"
  "@typescript-eslint/no-misused-promises":
    - "error"
  "@typescript-eslint/await-thenable":
    - "error"
