name: test

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: dependencies
        run: npm i --dev
      - name: run test
        run: npm test
